name: demo
description: "BrainHub, where ideas come alive"
publish_to: 'none' # Keep this for personal use

# App version
version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  shared_preferences: ^2.1.0
  image_picker: ^1.1.1
  intl: ^0.18.0
  timeago: ^3.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.10.0

# Flutter Launcher Icons configuration
flutter_icons:
  android: true
  ios: false
  image_path: "assets/logo.jpeg"

flutter:
  uses-material-design: true

  assets:
    - assets/
